name: HJYHunt
version: 3.1
main: net.mcxk.hjyhunt.HJYHunt
api-version: 1.16
# 未使用: NoteBlockAPI
soft-depend: [ AdvancedReplay, PlaceholderAPI ]

commands:
  minehunt:
    description: 猎人游戏指令
    usage: /<command> [copyright|hunter|runner|resetcountdown|players|forcestart|want|prepare]


