name: HJYHunt
version: 3.2#HotFix1
main: net.mcxk.hjyhunt.HJYHunt
api-version: 1.16
  # 未使用: NoteBlockAPI
soft-depend: [ AdvancedReplay, PlaceholderAPI ]

commands:
  hjyhunt:
    description: 猎人游戏指令
    usage: /<command> [about|hunter|runner|rstcd|players|start|want|prepare]
